"""
QA Report Export Module for NovelTrad.
Generates PDF and HTML reports for quality assurance checks.
Conforms to §12.9.1 of the specification.
"""
import os
from datetime import datetime
from typing import List, Optional
from src.core.qa_checker import QAIssue


class QAReportExporter:
    """Export QA check results to PDF or HTML."""

    def __init__(self, project_name: str = "NovelTrad Project"):
        self.project_name = project_name
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    def export_html(self, issues: List[QAIssue], output_path: str) -> str:
        """
        Export QA issues to HTML report.
        
        Args:
            issues: List of QAIssue objects
            output_path: Path for output HTML file
            
        Returns:
            Path to generated HTML file
        """
        # Group issues by severity
        errors = [i for i in issues if i.severity == 'error']
        warnings = [i for i in issues if i.severity == 'warning']
        infos = [i for i in issues if i.severity == 'info']
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QA Report - {self.project_name}</title>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; background: #1a1a1a; color: #e0e0e0; }}
        h1 {{ color: #3b82f6; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }}
        h2 {{ color: #60a5fa; margin-top: 30px; }}
        .summary {{ display: flex; gap: 20px; margin: 20px 0; }}
        .stat {{ background: #2a2a2a; padding: 15px 25px; border-radius: 8px; text-align: center; }}
        .stat-number {{ font-size: 2em; font-weight: bold; }}
        .stat-label {{ color: #9ca3af; font-size: 0.9em; }}
        .errors {{ color: #ef4444; }}
        .warnings {{ color: #f59e0b; }}
        .infos {{ color: #3b82f6; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #404040; }}
        th {{ background: #2a2a2a; color: #60a5fa; }}
        tr:hover {{ background: #252525; }}
        .severity-error {{ color: #ef4444; font-weight: bold; }}
        .severity-warning {{ color: #f59e0b; font-weight: bold; }}
        .severity-info {{ color: #3b82f6; }}
        .issue-type {{ font-family: monospace; background: #333; padding: 2px 6px; border-radius: 4px; }}
        .footer {{ margin-top: 40px; color: #6b7280; font-size: 0.9em; }}
    </style>
</head>
<body>
    <h1>🔍 QA Report - {self.project_name}</h1>
    <p>Generated: {self.timestamp}</p>
    
    <div class="summary">
        <div class="stat">
            <div class="stat-number errors">{len(errors)}</div>
            <div class="stat-label">Errors</div>
        </div>
        <div class="stat">
            <div class="stat-number warnings">{len(warnings)}</div>
            <div class="stat-label">Warnings</div>
        </div>
        <div class="stat">
            <div class="stat-number infos">{len(infos)}</div>
            <div class="stat-label">Info</div>
        </div>
        <div class="stat">
            <div class="stat-number">{len(issues)}</div>
            <div class="stat-label">Total Issues</div>
        </div>
    </div>
"""
        
        if errors:
            html += f"\n    <h2 class='errors'>❌ Errors ({len(errors)})</h2>\n    <table>\n        <tr><th>Seg #</th><th>Type</th><th>Message</th><th>Source</th></tr>\n"
            for issue in errors:
                html += f"        <tr><td>{issue.segment_index}</td><td><span class='issue-type'>{issue.issue_type}</span></td><td>{issue.message}</td><td>{self._truncate(issue.source_text, 50)}</td></tr>\n"
            html += "    </table>\n"
        
        if warnings:
            html += f"\n    <h2 class='warnings'>⚠️ Warnings ({len(warnings)})</h2>\n    <table>\n        <tr><th>Seg #</th><th>Type</th><th>Message</th><th>Source</th></tr>\n"
            for issue in warnings:
                html += f"        <tr><td>{issue.segment_index}</td><td><span class='issue-type'>{issue.issue_type}</span></td><td>{issue.message}</td><td>{self._truncate(issue.source_text, 50)}</td></tr>\n"
            html += "    </table>\n"
        
        if infos:
            html += f"\n    <h2 class='infos'>ℹ️ Info ({len(infos)})</h2>\n    <table>\n        <tr><th>Seg #</th><th>Type</th><th>Message</th><th>Source</th></tr>\n"
            for issue in infos:
                html += f"        <tr><td>{issue.segment_index}</td><td><span class='issue-type'>{issue.issue_type}</span></td><td>{issue.message}</td><td>{self._truncate(issue.source_text, 50)}</td></tr>\n"
            html += "    </table>\n"
        
        html += f"""
    <div class="footer">
        <p>Generated by NovelTrad QA Module</p>
    </div>
</body>
</html>"""
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)
        
        return output_path

    def export_pdf(self, issues: List[QAIssue], output_path: str) -> str:
        """
        Export QA issues to PDF report.
        
        Args:
            issues: List of QAIssue objects
            output_path: Path for output PDF file
            
        Returns:
            Path to generated PDF file
        """
        try:
            from weasyprint import HTML
        except ImportError:
            # Fallback to HTML if weasyprint not available
            html_path = output_path.replace('.pdf', '.html')
            self.export_html(issues, html_path)
            return html_path
        
        # Generate HTML content
        html_path = output_path.replace('.pdf', '_temp.html')
        self.export_html(issues, html_path)
        
        # Convert to PDF
        HTML(filename=html_path).write_pdf(output_path)
        
        # Clean up temp HTML
        if os.path.exists(html_path):
            os.remove(html_path)
        
        return output_path

    def _truncate(self, text: str, max_length: int) -> str:
        """Truncate text with ellipsis."""
        if len(text) <= max_length:
            return text
        return text[:max_length-3] + "..."


def generate_qa_report(issues: List[QAIssue], project_name: str, 
                       format: str = 'html', output_dir: str = '.') -> str:
    """
    Generate QA report in specified format.
    
    Args:
        issues: List of QAIssue objects
        project_name: Name of the project
        format: 'html' or 'pdf'
        output_dir: Output directory for the report
        
    Returns:
        Path to generated report
    """
    exporter = QAReportExporter(project_name)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    if format.lower() == 'pdf':
        output_path = os.path.join(output_dir, f"qa_report_{timestamp}.pdf")
        return exporter.export_pdf(issues, output_path)
    else:
        output_path = os.path.join(output_dir, f"qa_report_{timestamp}.html")
        return exporter.export_html(issues, output_path)
